title: Esoteric Enderman
description: >
  This is my personal website made using Academic Pages.

repository: "enderman.dev"

name: &name "Esoteric Enderman"

author:
  name: "Esoteric Enderman"
  avatar: "profile.png"
  bio: "My bio statement"
  location: "Location"
  github: esotericenderman
  email: esotericenderman@gmail.com

title_separator: "-"

url: "https://enderman.dev"
baseurl: ""
markdown: kramdown

email: esotericenderman@gmail.com
github_username: esotericenderman

remote_theme: academicpages/academicpages.github.io
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
