# Site settings
title: Esoteric Enderman
email: esotericenderman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal website made using Academic Pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://enderman.dev" # the base hostname & protocol for your site
github_username: esotericenderman

# Build settings
markdown: kramdown
remote_theme: academicpages/academicpages.github.io
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

# Site Author
author:
  name: "Esoteric Enderman"
  avatar: "profile.png"
  bio: "My bio statement" # Add a short bio here
  location: "Location"
  github: esotericenderman
  email: esotericenderman@gmail.com
  # Add more social profiles if desired
  # linkedin: your-linkedin
  # twitter: your-twitter
  # Add other links that will appear in your sidebar

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
