title: Esoteric Enderman
description: >
  This is my personal website made using Academic Pages.

repository: "enderman.dev"

name: &name "Esoteric Enderman"
description: &description "I'm an ambitious software developer with an interest for maths and game development."

author:
  name: "Esoteric Enderman"
  avatar: "profile.png"
  bio: "I'm an ambitious software developer with an interest for maths and game development."
  location: "Internet"
  github: esotericenderman
  email: esotericenderman@gmail.com
  discord: esotericenderman
  gitlab: esotericenderman
  npm: esotericenderman
  modrinth: esotericenderman
  youtube: esotericenderman
  namemc: esotericenderman

title_separator: "-"

url: "https://enderman.dev"
baseurl: ""
markdown: kramdown

email: esotericenderman@gmail.com
github_username: esotericenderman

locale: "en-UK"

remote_theme: academicpages/academicpages.github.io
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

atom_feed:
  path: false

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
