# Site settings
title: Esoteric Enderman
email: esotericenderman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal website made using Academic Pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://enderman.dev" # the base hostname & protocol for your site
github_username: esotericenderman

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
